unisystem_notice_notice:
    resource: "@UnisystemNoticeBundle/Resources/config/routing/notice.yml"
    prefix:   /notice

unisystem_notice_category:
    resource: "@UnisystemNoticeBundle/Resources/config/routing/noticecategory.yml"
    prefix:   /category

unisystem_notice_photography:
    resource: "@UnisystemNoticeBundle/Resources/config/routing/noticephotography.yml"
    prefix:   /photography

