fos_user_security_login:
    path:     /login
    defaults: { _controller: "UnisystemUserBundle:Security:login" }
    methods: [GET|POST]

fos_user_security_check:
    path:     /login_check
    defaults: { _controller: "UnisystemUserBundle:Security:check" }
    methods: [POST]

fos_user_security_logout:
    path:     /logout
    defaults: { _controller: "UnisystemUserBundle:Security:logout" }
    methods: [GET]
