<?php

namespace Unisystem\AdminBundle\Entity;

/**
 * AcademyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcademyRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFrontpageList()
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('a')
            ->from('UnisystemAdminBundle:Academy', 'a')
            ->getQuery();

        return $qb->getResult();
    }
}
