<?php

namespace Unisystem\AdminBundle\Entity;

/**
 * AcademyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcademyRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFrontpageList()
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('a')
            ->from('UnisystemAdminBundle:Academy', 'a')
            ->getQuery();

        return $qb->getResult();
    }
    public function getFutureList($sort = null, $direction = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('a')
            ->from('UnisystemAdminBundle:Academy', 'a')
            ->where('a.schedule > :datetime')
            ->setParameter('datetime', new \DateTime());

        if($sort && $direction)
        {
            $sort = 'a.'.$sort;
            $qb ->orderBy($sort, $direction);
        }

        return $qb->getQuery()->getResult();
    }
    public function getPastList($sort = null, $direction = null)
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('a')
            ->from('UnisystemAdminBundle:Academy', 'a')
            ->where('a.schedule < :datetime')
            ->setParameter('datetime', new \DateTime());

        if($sort && $direction)
        {
            $sort = 'a.'.$sort;
            $qb ->orderBy($sort, $direction);
        }

        return $qb->getQuery()->getResult();
    }

}
