<?php

namespace Unisystem\AdminBundle\Entity;

/**
 * MainPhotographyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainPhotographyRepository extends \Doctrine\ORM\EntityRepository
{
}
