<?php

namespace Unisystem\AdminBundle\Entity;

/**
 * NoticePhotographyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticePhotographyRepository extends \Doctrine\ORM\EntityRepository
{
}
