<?php

namespace Unisystem\AdminBundle\Entity;

/**
 * ResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFrontpageList()
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('r')
            ->from('UnisystemAdminBundle:Resource', 'r')
            ->getQuery();

        return $qb->getResult();
    }
}
