admin_module_index:
    path:     /
    defaults: { _controller: "UnisystemAdminBundle:AdminModule:index" }
    methods:  GET

admin_module_show:
    path:     /{id}/show
    defaults: { _controller: "UnisystemAdminBundle:AdminModule:show" }
    methods:  GET

admin_module_new:
    path:     /new
    defaults: { _controller: "UnisystemAdminBundle:AdminModule:new" }
    methods:  [GET, POST]

admin_module_edit:
    path:     /{id}/edit
    defaults: { _controller: "UnisystemAdminBundle:AdminModule:edit" }
    methods:  [GET, POST]

admin_module_delete:
    path:     /{id}/delete
    defaults: { _controller: "UnisystemAdminBundle:AdminModule:delete" }
    methods:  DELETE
