resource_index:
    path:     /
    defaults: { _controller: "UnisystemAdminBundle:Resource:index" }
    methods:  GET

resource_show:
    path:     /{id}/show
    defaults: { _controller: "UnisystemAdminBundle:Resource:show" }
    methods:  GET

resource_new:
    path:     /new
    defaults: { _controller: "UnisystemAdminBundle:Resource:new" }
    methods:  [GET, POST]

resource_edit:
    path:     /{id}/edit
    defaults: { _controller: "UnisystemAdminBundle:Resource:edit" }
    methods:  [GET, POST]

resource_delete:
    path:     /{id}/delete
    defaults: { _controller: "UnisystemAdminBundle:Resource:delete" }
    methods:  DELETE
