member_role_index:
    path:     /
    defaults: { _controller: "UnisystemMemberBundle:MemberRole:index" }
    methods:  GET

member_role_show:
    path:     /{id}/show
    defaults: { _controller: "UnisystemMemberBundle:MemberRole:show" }
    methods:  GET

member_role_new:
    path:     /new
    defaults: { _controller: "UnisystemMemberBundle:MemberRole:new" }
    methods:  [GET, POST]

member_role_edit:
    path:     /{id}/edit
    defaults: { _controller: "UnisystemMemberBundle:MemberRole:edit" }
    methods:  [GET, POST]

member_role_delete:
    path:     /{id}/delete
    defaults: { _controller: "UnisystemMemberBundle:MemberRole:delete" }
    methods:  DELETE
