notice_index:
    path:     /
    defaults: { _controller: "UnisystemNoticeBundle:Notice:index" }
    methods:  GET

notice_show:
    path:     /{id}/show
    defaults: { _controller: "UnisystemNoticeBundle:Notice:show" }
    methods:  GET

notice_new:
    path:     /new
    defaults: { _controller: "UnisystemNoticeBundle:Notice:new" }
    methods:  [GET, POST]

notice_edit:
    path:     /{id}/edit
    defaults: { _controller: "UnisystemNoticeBundle:Notice:edit" }
    methods:  [GET, POST]

notice_delete:
    path:     /{id}/delete
    defaults: { _controller: "UnisystemNoticeBundle:Notice:delete" }
    methods:  DELETE
