notice_category_index:
    path:     /
    defaults: { _controller: "UnisystemNoticeBundle:NoticeCategory:index" }
    methods:  GET

notice_category_show:
    path:     /{id}/show
    defaults: { _controller: "UnisystemNoticeBundle:NoticeCategory:show" }
    methods:  GET

notice_category_new:
    path:     /new
    defaults: { _controller: "UnisystemNoticeBundle:NoticeCategory:new" }
    methods:  [GET, POST]

notice_category_edit:
    path:     /{id}/edit
    defaults: { _controller: "UnisystemNoticeBundle:NoticeCategory:edit" }
    methods:  [GET, POST]

notice_category_delete:
    path:     /{id}/delete
    defaults: { _controller: "UnisystemNoticeBundle:NoticeCategory:delete" }
    methods:  DELETE
