# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

#    access_denied_url:    ~
    encoders:
#        FOS\UserBundle\Model\UserInterface: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
#        chain_provider:
#            chain:
#                providers: [in_memory, unisystem_userbundle]
        in_memory:
            memory:
                users:
                    root: { password: %root_password%, roles: 'ROLE_ADMIN' }
#        unisystem_userbundle:
#            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:   ^/
            anonymous: true
#            http_basic:
#                realm: "Secured Area"
            form_login:
                login_path: /login
                failure_path: /login
                check_path: /login
                always_use_default_target_path: true
                default_target_path: /admin/notice
                csrf_token_generator: security.csrf.token_manager
                failure_path: /login
            logout:
                path:   /logout
                target: /login


    access_control:
        - { path: ^/login, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/register, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/resetting, roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/admin, roles: [ROLE_ADMIN] }
