unisystem_product_product:
    resource: "@UnisystemProductBundle/Resources/config/routing/product.yml"
    prefix:   /product

unisystem_product_category:
    resource: "@UnisystemProductBundle/Resources/config/routing/productcategory.yml"
    prefix:   /category

unisystem_product_photography:
    resource: "@UnisystemProductBundle/Resources/config/routing/productphotography.yml"
    prefix:   /photography

unisystem_product_property:
    resource: "@UnisystemProductBundle/Resources/config/routing/productproperty.yml"
    prefix:   /property
