Unisystem\AdminBundle\Entity\Notice:
    type: entity
    table: Notice
    repositoryClass: Unisystem\AdminBundle\Entity\NoticeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        photographies:
            targetEntity: Unisystem\AdminBundle\Entity\NoticePhotography
            mappedBy: notice
            cascade: ['persist', merge]
    fields:
        title:
            type: string
            length: 300
            nullable: true
        content:
            type: text
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            nullable: true
    gedmo:
        soft_deleteable:
            field_name: deletedAt
            time_aware: false
    lifecycleCallbacks: {  }
