unisystem_member_member:
    resource: "@UnisystemMemberBundle/Resources/config/routing/member.yml"
    prefix:   /member

unisystem_member_course:
    resource: "@UnisystemMemberBundle/Resources/config/routing/membercourse.yml"
    prefix:   /course

unisystem_member_role:
    resource: "@UnisystemMemberBundle/Resources/config/routing/memberrole.yml"
    prefix:   /role
