page_index:
    path:     /
    defaults: { _controller: "UnisystemPageBundle:Page:index" }
    methods:  GET

page_show:
    path:     /{id}/show
    defaults: { _controller: "UnisystemPageBundle:Page:show" }
    methods:  GET

page_new:
    path:     /new
    defaults: { _controller: "UnisystemPageBundle:Page:new" }
    methods:  [GET, POST]

page_edit:
    path:     /{id}/edit
    defaults: { _controller: "UnisystemPageBundle:Page:edit" }
    methods:  [GET, POST]

page_delete:
    path:     /{id}/delete
    defaults: { _controller: "UnisystemPageBundle:Page:delete" }
    methods:  DELETE
