page_service_index:
    path:     /
    defaults: { _controller: "UnisystemPageBundle:PageService:index" }
    methods:  GET

page_service_show:
    path:     /{id}/show
    defaults: { _controller: "UnisystemPageBundle:PageService:show" }
    methods:  GET

page_service_new:
    path:     /new
    defaults: { _controller: "UnisystemPageBundle:PageService:new" }
    methods:  [GET, POST]

page_service_edit:
    path:     /{id}/edit
    defaults: { _controller: "UnisystemPageBundle:PageService:edit" }
    methods:  [GET, POST]

page_service_delete:
    path:     /{id}/delete
    defaults: { _controller: "UnisystemPageBundle:PageService:delete" }
    methods:  DELETE
