page_process_index:
    path:     /
    defaults: { _controller: "UnisystemPageBundle:PageProcess:index" }
    methods:  GET

page_process_show:
    path:     /{id}/show
    defaults: { _controller: "UnisystemPageBundle:PageProcess:show" }
    methods:  GET

page_process_new:
    path:     /new
    defaults: { _controller: "UnisystemPageBundle:PageProcess:new" }
    methods:  [GET, POST]

page_process_edit:
    path:     /{id}/edit
    defaults: { _controller: "UnisystemPageBundle:PageProcess:edit" }
    methods:  [GET, POST]

page_process_delete:
    path:     /{id}/delete
    defaults: { _controller: "UnisystemPageBundle:PageProcess:delete" }
    methods:  DELETE
