page_publication_index:
    path:     /
    defaults: { _controller: "UnisystemPageBundle:PagePublication:index" }
    methods:  GET

page_publication_show:
    path:     /{id}/show
    defaults: { _controller: "UnisystemPageBundle:PagePublication:show" }
    methods:  GET

page_publication_new:
    path:     /new
    defaults: { _controller: "UnisystemPageBundle:PagePublication:new" }
    methods:  [GET, POST]

page_publication_edit:
    path:     /{id}/edit
    defaults: { _controller: "UnisystemPageBundle:PagePublication:edit" }
    methods:  [GET, POST]

page_publication_delete:
    path:     /{id}/delete
    defaults: { _controller: "UnisystemPageBundle:PagePublication:delete" }
    methods:  DELETE
