services:
    unisystem_resource.form.type.resource_photography:
        class: Unisystem\ResourceBundle\Form\ResourcePhotographyType
        arguments: ['@vich_uploader.storage', '@vich_uploader.upload_handler', '@translator']
        tags:
            - { name: form.type, alias: resource_photography }
#    unisystem_resource.example:
#        class: Unisystem\ResourceBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
