product_photography_index:
    path:     /
    defaults: { _controller: "UnisystemProductBundle:ProductPhotography:index" }
    methods:  GET

product_photography_show:
    path:     /{id}/show
    defaults: { _controller: "UnisystemProductBundle:ProductPhotography:show" }
    methods:  GET

product_photography_new:
    path:     /new
    defaults: { _controller: "UnisystemProductBundle:ProductPhotography:new" }
    methods:  [GET, POST]

product_photography_edit:
    path:     /{id}/edit
    defaults: { _controller: "UnisystemProductBundle:ProductPhotography:edit" }
    methods:  [GET, POST]

product_photography_delete:
    path:     /{id}/delete
    defaults: { _controller: "UnisystemProductBundle:ProductPhotography:delete" }
    methods:  DELETE
