product_category_index:
    path:     /
    defaults: { _controller: "UnisystemProductBundle:ProductCategory:index" }
    methods:  GET

product_category_show:
    path:     /{id}/show
    defaults: { _controller: "UnisystemProductBundle:ProductCategory:show" }
    methods:  GET

product_category_new:
    path:     /new
    defaults: { _controller: "UnisystemProductBundle:ProductCategory:new" }
    methods:  [GET, POST]

product_category_edit:
    path:     /{id}/edit
    defaults: { _controller: "UnisystemProductBundle:ProductCategory:edit" }
    methods:  [GET, POST]

product_category_delete:
    path:     /{id}/delete
    defaults: { _controller: "UnisystemProductBundle:ProductCategory:delete" }
    methods:  DELETE
