product_property_index:
    path:     /
    defaults: { _controller: "UnisystemProductBundle:ProductProperty:index" }
    methods:  GET

product_property_show:
    path:     /{id}/show
    defaults: { _controller: "UnisystemProductBundle:ProductProperty:show" }
    methods:  GET

product_property_new:
    path:     /new
    defaults: { _controller: "UnisystemProductBundle:ProductProperty:new" }
    methods:  [GET, POST]

product_property_edit:
    path:     /{id}/edit
    defaults: { _controller: "UnisystemProductBundle:ProductProperty:edit" }
    methods:  [GET, POST]

product_property_delete:
    path:     /{id}/delete
    defaults: { _controller: "UnisystemProductBundle:ProductProperty:delete" }
    methods:  DELETE
